In [ ]:
import pandas as pd
import numpy as np

path = '/content/INDECOPI_OPS1_Millon.csv'
df = pd.read_csv(path, sep=None, engine='python')

In [ ]:
stats_df = pd.DataFrame({
    'Type': df.dtypes,
    'Unique Values': df.nunique(),
    'Missing Values': df.isnull().sum(),
    'Missing %': (df.isnull().sum() / len(df) * 100).round(2)
})

print('Summary Statistics per Column:')
display(stats_df)

def get_duplicate_columns(df):
    duplicate_column_names = set()
    for x in range(df.shape[1]):
        col = df.iloc[:, x]
        for y in range(x + 1, df.shape[1]):
            other_col = df.iloc[:, y]
            if col.equals(other_col):
                duplicate_column_names.add(df.columns.values[y])
    return list(duplicate_column_names)

duplicates = get_duplicate_columns(df)
print(f'\nRepeated (identical) columns found: {duplicates if duplicates else "None"}')

print(f'\nShape of the dataset: {df.shape}')
display(df.head())

Summary Statistics per Column:

                         Type  Unique Values  Missing Values  Missing %
﻿VC_LUGAR              object              1               0       0.00
VC_TIPO_EXPEDIENTE     object              7               0       0.00
EMPLEADO               object             27               0       0.00
FEC_PRE                object              1               0       0.00
FEC_REING              object            541          628972      62.90
NRO_EXPEDIENTE         object        1000000               0       0.00
FEC_CAL                object            546               0       0.00
SAC                     int64              2               0       0.00
COD_C                  object              1               0       0.00
VC_RUBRO               object             36          118617      11.86
DENUNCIANTES           object         865237               0       0.00
RUC_DENUNCIADOS        object           1382             830       0.08
DENUNCIADOS            object           1550             830       0.08
EXPEDIENTE_PRINCIPAL  float64              0         1000000     100.00
AREA_CPC              float64              0         1000000     100.00
EXP_ORIGEN_ORPS       float64              0         1000000     100.00
DESCR_CIIU             object            103          118617      11.86

Repeated (identical) columns found: ['AREA_CPC', 'EXP_ORIGEN_ORPS']

Shape of the dataset: (1000000, 17)

,﻿VC_LUGAR,VC_TIPO_EXPEDIENTE,EMPLEADO,FEC_PRE,FEC_REING,NRO_EXPEDIENTE,FEC_CAL,SAC,COD_C,VC_RUBRO,DENUNCIANTES,RUC_DENUNCIADOS,DENUNCIADOS,EXPEDIENTE_PRINCIPAL,AREA_CPC,EXP_ORIGEN_ORPS,DESCR_CIIU
0,SEDE CENTRAL,INCUM.LIQUID.DE COSTAS Y COSTOS,ROCA ORTEGA PAMELA,1970-01-01,NaN,000001-1970/PS1,1971-03-29,0,Z,TRANSPORTE POR VIA AEREA,"VALDEZ DELGADO, GLORIA BRIGITTE",20467534026,AMERICA MOVIL PERU S.A.C.,NaN,NaN,NaN,Transporte regular por vía aérea
1,SEDE CENTRAL,DENUNCIA,JIMENEZ CHAVEZ CATHERINE JOAHNA,1970-01-01,1970-01-21,000002-1970/PS1,1970-02-12,0,Z,CONSTRUCCION E INMOBILIARIOS,"MORALES DELGADO, OSCAR CARMEN",20467534026,AMERICA MOVIL PERU S.A.C.,NaN,NaN,NaN,Actividades inmobiliarias realizadas con biene...
2,SEDE CENTRAL,INCUMPL. DE MEDIDAS CORRECTIVAS,QUIROZ LEON CLAUDIA ESMERALDA,1970-01-01,NaN,000003-1970/PS1,1970-04-11,0,Z,TRANSPORTE TERRESTRE Y OTROS TIPOS DE TRANSPORTE,"DIAZ RAMOS, LUCIA VERONICA",20100070970,SUPERMERCADOS PERUANOS SOCIEDAD ANONIMA 'O ' S...,NaN,NaN,NaN,Otros tipos de transporte regular de pasajeros...
3,SEDE CENTRAL,INCUMPL. DE ACUERDO CONCILIATORIO SAC,MEZA CALLE LUIS ELIAS,1970-01-01,NaN,000004-1970/PS1,1970-02-15,0,Z,FABRICACION DE MUEBLES,"FUENTES ALVAREZ, KATHERINE VALERIA",20100041953,RIMAC SEGUROS Y REASEGUROS,NaN,NaN,NaN,Fabricación de muebles
4,SEDE CENTRAL,DENUNCIA,PALOMINO QUINTO MILUSKA,1970-01-01,NaN,000005-1970/PS1,1970-02-13,0,Z,SEGUROS Y PENSIONES,"LOPEZ MORALES, DANIEL MANUEL",20341841357,LAN PERU S.A.,NaN,NaN,NaN,Planes de seguros generales

In [ ]:
cols_to_keep = [col for col in df.columns if df[col].nunique() > 2]
cols_to_drop = [col for col in df.columns if df[col].nunique() <= 2]

df_filtered = df[cols_to_keep].copy()

print(f'Columns removed: {cols_to_drop}')
print(f'Original shape: {df.shape}')
print(f'New shape: {df_filtered.shape}')
display(df_filtered.head())

Columns removed: ['\ufeffVC_LUGAR', 'FEC_PRE', 'SAC', 'COD_C', 'EXPEDIENTE_PRINCIPAL', 'AREA_CPC', 'EXP_ORIGEN_ORPS']
Original shape: (1000000, 17)
New shape: (1000000, 10)

,VC_TIPO_EXPEDIENTE,EMPLEADO,FEC_REING,NRO_EXPEDIENTE,FEC_CAL,VC_RUBRO,DENUNCIANTES,RUC_DENUNCIADOS,DENUNCIADOS,DESCR_CIIU
0,INCUM.LIQUID.DE COSTAS Y COSTOS,ROCA ORTEGA PAMELA,NaN,000001-1970/PS1,1971-03-29,TRANSPORTE POR VIA AEREA,"VALDEZ DELGADO, GLORIA BRIGITTE",20467534026,AMERICA MOVIL PERU S.A.C.,Transporte regular por vía aérea
1,DENUNCIA,JIMENEZ CHAVEZ CATHERINE JOAHNA,1970-01-21,000002-1970/PS1,1970-02-12,CONSTRUCCION E INMOBILIARIOS,"MORALES DELGADO, OSCAR CARMEN",20467534026,AMERICA MOVIL PERU S.A.C.,Actividades inmobiliarias realizadas con biene...
2,INCUMPL. DE MEDIDAS CORRECTIVAS,QUIROZ LEON CLAUDIA ESMERALDA,NaN,000003-1970/PS1,1970-04-11,TRANSPORTE TERRESTRE Y OTROS TIPOS DE TRANSPORTE,"DIAZ RAMOS, LUCIA VERONICA",20100070970,SUPERMERCADOS PERUANOS SOCIEDAD ANONIMA 'O ' S...,Otros tipos de transporte regular de pasajeros...
3,INCUMPL. DE ACUERDO CONCILIATORIO SAC,MEZA CALLE LUIS ELIAS,NaN,000004-1970/PS1,1970-02-15,FABRICACION DE MUEBLES,"FUENTES ALVAREZ, KATHERINE VALERIA",20100041953,RIMAC SEGUROS Y REASEGUROS,Fabricación de muebles
4,DENUNCIA,PALOMINO QUINTO MILUSKA,NaN,000005-1970/PS1,1970-02-13,SEGUROS Y PENSIONES,"LOPEZ MORALES, DANIEL MANUEL",20341841357,LAN PERU S.A.,Planes de seguros generales

In [ ]:
df_filtered.head()

,VC_TIPO_EXPEDIENTE,EMPLEADO,FEC_REING,NRO_EXPEDIENTE,FEC_CAL,VC_RUBRO,DENUNCIANTES,RUC_DENUNCIADOS,DENUNCIADOS,DESCR_CIIU
0,INCUM.LIQUID.DE COSTAS Y COSTOS,ROCA ORTEGA PAMELA,NaN,000001-1970/PS1,1971-03-29,TRANSPORTE POR VIA AEREA,"VALDEZ DELGADO, GLORIA BRIGITTE",20467534026,AMERICA MOVIL PERU S.A.C.,Transporte regular por vía aérea
1,DENUNCIA,JIMENEZ CHAVEZ CATHERINE JOAHNA,1970-01-21,000002-1970/PS1,1970-02-12,CONSTRUCCION E INMOBILIARIOS,"MORALES DELGADO, OSCAR CARMEN",20467534026,AMERICA MOVIL PERU S.A.C.,Actividades inmobiliarias realizadas con biene...
2,INCUMPL. DE MEDIDAS CORRECTIVAS,QUIROZ LEON CLAUDIA ESMERALDA,NaN,000003-1970/PS1,1970-04-11,TRANSPORTE TERRESTRE Y OTROS TIPOS DE TRANSPORTE,"DIAZ RAMOS, LUCIA VERONICA",20100070970,SUPERMERCADOS PERUANOS SOCIEDAD ANONIMA 'O ' S...,Otros tipos de transporte regular de pasajeros...
3,INCUMPL. DE ACUERDO CONCILIATORIO SAC,MEZA CALLE LUIS ELIAS,NaN,000004-1970/PS1,1970-02-15,FABRICACION DE MUEBLES,"FUENTES ALVAREZ, KATHERINE VALERIA",20100041953,RIMAC SEGUROS Y REASEGUROS,Fabricación de muebles
4,DENUNCIA,PALOMINO QUINTO MILUSKA,NaN,000005-1970/PS1,1970-02-13,SEGUROS Y PENSIONES,"LOPEZ MORALES, DANIEL MANUEL",20341841357,LAN PERU S.A.,Planes de seguros generales

In [ ]:
null_pct = df_filtered.isnull().sum() / len(df_filtered) * 100

cols_with_many_nulls = null_pct[null_pct > 10].index.tolist()

cols_to_drop_manually = ['EMPLEADO', 'NRO_EXPEDIENTE']
df_filtered = df_filtered.drop(columns=cols_with_many_nulls + cols_to_drop_manually)

print(f'Columns removed (>10% nulls): {cols_with_many_nulls}')
print(f'Columns removed manually: {cols_to_drop_manually}')
print(f'Remaining columns: {df_filtered.columns.tolist()}')
print(f'Final shape: {df_filtered.shape}')
display(df_filtered.head())

Columns removed (>10% nulls): []
Columns removed manually: ['EMPLEADO', 'NRO_EXPEDIENTE']
Remaining columns: ['VC_TIPO_EXPEDIENTE', 'FEC_CAL', 'DENUNCIANTES', 'RUC_DENUNCIADOS', 'DENUNCIADOS']
Final shape: (1000000, 5)

,VC_TIPO_EXPEDIENTE,FEC_CAL,DENUNCIANTES,RUC_DENUNCIADOS,DENUNCIADOS
0,INCUM.LIQUID.DE COSTAS Y COSTOS,1971-03-29,"VALDEZ DELGADO, GLORIA BRIGITTE",20467534026,AMERICA MOVIL PERU S.A.C.
1,DENUNCIA,1970-02-12,"MORALES DELGADO, OSCAR CARMEN",20467534026,AMERICA MOVIL PERU S.A.C.
2,INCUMPL. DE MEDIDAS CORRECTIVAS,1970-04-11,"DIAZ RAMOS, LUCIA VERONICA",20100070970,SUPERMERCADOS PERUANOS SOCIEDAD ANONIMA 'O ' S...
3,INCUMPL. DE ACUERDO CONCILIATORIO SAC,1970-02-15,"FUENTES ALVAREZ, KATHERINE VALERIA",20100041953,RIMAC SEGUROS Y REASEGUROS
4,DENUNCIA,1970-02-13,"LOPEZ MORALES, DANIEL MANUEL",20341841357,LAN PERU S.A.

In [ ]:
final_stats = pd.DataFrame({
    'Type': df_filtered.dtypes,
    'Unique Values': df_filtered.nunique(),
    'Missing Values': df_filtered.isnull().sum(),
    'Missing %': (df_filtered.isnull().sum() / len(df_filtered) * 100).round(2)
})

print('Final Dataset Summary Statistics:')
display(final_stats)

Final Dataset Summary Statistics:

                      Type  Unique Values  Missing Values  Missing %
VC_TIPO_EXPEDIENTE  object              7               0       0.00
FEC_CAL             object            546               0       0.00
DENUNCIANTES        object         865237               0       0.00
RUC_DENUNCIADOS     object           1382             830       0.08
DENUNCIADOS         object           1550             830       0.08

In [ ]:
import re
import unicodedata

def normalize_text(text):
    if pd.isna(text) or not isinstance(text, str):
        return text
    text = text.upper()
    text = ''.join(c for c in unicodedata.normalize('NFKD', text) if unicodedata.category(c) != 'Mn')
    text = re.sub(r'[^A-Z0-9 ]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

cols_to_normalize = ['VC_TIPO_EXPEDIENTE', 'DENUNCIANTES', 'DENUNCIADOS']

for col in cols_to_normalize:
    print(f'Normalizing {col}...')
    df_filtered[col] = df_filtered[col].apply(normalize_text)

print('\nNormalization complete. Preview of cleaned data:')
display(df_filtered.head())

Normalizing VC_TIPO_EXPEDIENTE...
Normalizing DENUNCIANTES...
Normalizing DENUNCIADOS...

Normalization complete. Preview of cleaned data:

,VC_TIPO_EXPEDIENTE,FEC_CAL,DENUNCIANTES,RUC_DENUNCIADOS,DENUNCIADOS
0,INCUM LIQUID DE COSTAS Y COSTOS,1971-03-29,VALDEZ DELGADO GLORIA BRIGITTE,20467534026,AMERICA MOVIL PERU S A C
1,DENUNCIA,1970-02-12,MORALES DELGADO OSCAR CARMEN,20467534026,AMERICA MOVIL PERU S A C
2,INCUMPL DE MEDIDAS CORRECTIVAS,1970-04-11,DIAZ RAMOS LUCIA VERONICA,20100070970,SUPERMERCADOS PERUANOS SOCIEDAD ANONIMA O S P S A
3,INCUMPL DE ACUERDO CONCILIATORIO SAC,1970-02-15,FUENTES ALVAREZ KATHERINE VALERIA,20100041953,RIMAC SEGUROS Y REASEGUROS
4,DENUNCIA,1970-02-13,LOPEZ MORALES DANIEL MANUEL,20341841357,LAN PERU S A

In [ ]:
def determine_target_key(row):
    ruc = str(row['RUC_DENUNCIADOS']) if pd.notna(row['RUC_DENUNCIADOS']) else ''
    if len(ruc) == 11 and ruc.isdigit():
        return ruc
    return row['DENUNCIADOS']

df_filtered['USER_KEY'] = df_filtered['DENUNCIANTES']
df_filtered['TARGET_KEY'] = df_filtered.apply(determine_target_key, axis=1)
df_filtered['TYPE_KEY'] = df_filtered['VC_TIPO_EXPEDIENTE']

print('New key columns created:')
display(df_filtered[['USER_KEY', 'TARGET_KEY', 'TYPE_KEY']].head())

New key columns created:

,USER_KEY,TARGET_KEY,TYPE_KEY
0,VALDEZ DELGADO GLORIA BRIGITTE,20467534026,INCUM LIQUID DE COSTAS Y COSTOS
1,MORALES DELGADO OSCAR CARMEN,20467534026,DENUNCIA
2,DIAZ RAMOS LUCIA VERONICA,20100070970,INCUMPL DE MEDIDAS CORRECTIVAS
3,FUENTES ALVAREZ KATHERINE VALERIA,20100041953,INCUMPL DE ACUERDO CONCILIATORIO SAC
4,LOPEZ MORALES DANIEL MANUEL,20341841357,DENUNCIA

In [ ]:
df_filtered

,VC_TIPO_EXPEDIENTE,FEC_CAL,DENUNCIANTES,RUC_DENUNCIADOS,DENUNCIADOS,USER_KEY,TARGET_KEY,TYPE_KEY
0,INCUM LIQUID DE COSTAS Y COSTOS,1971-03-29,VALDEZ DELGADO GLORIA BRIGITTE,20467534026,AMERICA MOVIL PERU S A C,VALDEZ DELGADO GLORIA BRIGITTE,20467534026,INCUM LIQUID DE COSTAS Y COSTOS
1,DENUNCIA,1970-02-12,MORALES DELGADO OSCAR CARMEN,20467534026,AMERICA MOVIL PERU S A C,MORALES DELGADO OSCAR CARMEN,20467534026,DENUNCIA
2,INCUMPL DE MEDIDAS CORRECTIVAS,1970-04-11,DIAZ RAMOS LUCIA VERONICA,20100070970,SUPERMERCADOS PERUANOS SOCIEDAD ANONIMA O S P S A,DIAZ RAMOS LUCIA VERONICA,20100070970,INCUMPL DE MEDIDAS CORRECTIVAS
3,INCUMPL DE ACUERDO CONCILIATORIO SAC,1970-02-15,FUENTES ALVAREZ KATHERINE VALERIA,20100041953,RIMAC SEGUROS Y REASEGUROS,FUENTES ALVAREZ KATHERINE VALERIA,20100041953,INCUMPL DE ACUERDO CONCILIATORIO SAC
4,DENUNCIA,1970-02-13,LOPEZ MORALES DANIEL MANUEL,20341841357,LAN PERU S A,LOPEZ MORALES DANIEL MANUEL,20341841357,DENUNCIA
...,...,...,...,...,...,...,...,...
999995,DENUNCIA,1970-02-13,FUENTES SALAZAR MARTA RENATA,20102427891,TURISMO CIVA S A C,FUENTES SALAZAR MARTA RENATA,20102427891,DENUNCIA
999996,DENUNCIA,1970-10-12,AGUILAR HURTADO DAYANA,20513328819,BNP PARIBAS CARDIF S A COMPANIA DE SEGUROS Y R...,AGUILAR HURTADO DAYANA,20513328819,DENUNCIA
999997,LIQUIDACION DE COSTAS Y COSTOS,1970-02-16,RIVERA FUENTES SERGIO RAUL,20100041953,RIMAC SEGUROS Y REASEGUROS,RIVERA FUENTES SERGIO RAUL,20100041953,LIQUIDACION DE COSTAS Y COSTOS
999998,DENUNCIA,1970-02-13,SANCHEZ CARRILLO ANGELA MAXIMO,20521144620,AGENCIA EL BUEN HOGAR E I R L,SANCHEZ CARRILLO ANGELA MAXIMO,20521144620,DENUNCIA
999999,LIQUIDACION DE COSTAS Y COSTOS,1970-02-12,RIVERA RAMIREZ ROBERTO,20106897914,ENTEL PERU S A,RIVERA RAMIREZ ROBERTO,20106897914,LIQUIDACION DE COSTAS Y COSTOS

In [ ]:
from google.colab import files

output_filename = 'cleaned_dataset.csv'
df_filtered.to_csv(output_filename, index=False, encoding='utf-8')

print(f'File {output_filename} saved. Starting download...')
files.download(output_filename)

File cleaned_dataset.csv saved. Starting download...